language: ruby
rvm:
  - 2.4.1
services:
  - postgresql

bundler_args: "--without development --deployment"

cache: bundler

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rails db:migrate RAILS_ENV=test

env:
  - TEST_SUITE=controllers
  - TEST_SUITE=models

script: "bundle exec rails spec:$TEST_SUITE"